-- 教員データのインポート（50名）
INSERT INTO teachers (id, email, password, name, role, assigned_room_number, university_code, account_type, created_at, updated_at)
VALUES 
  (gen_random_uuid(), 'a', 'a', '田中', 'general', '101', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'b', 'b', '副田義樹', 'general', '102', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'c', 'c', '村瀬美樹', 'general', '103', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'd', 'd', '佐藤', 'general', '104', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'e', 'e', '石田俊介', 'general', '105', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'f', 'f', '加藤優奈', 'general', '106', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'g', 'g', '中村', 'general', '107', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'h', 'h', '小林優衣', 'general', '108', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'i', 'i', '山本拓海', 'general', '109', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'j', 'j', '渡辺', 'general', '110', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'k', 'k', '佐々木陽菜', 'general', '201', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'l', 'l', '高橋心', 'general', '202', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'm', 'm', '伊藤', 'general', '203', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'n', 'n', '田中悠斗', 'general', '204', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'o', 'o', '鈴木美咲', 'general', '205', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'p', 'p', '山田', 'general', '206', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'q', 'q', '佐藤葵', 'general', '207', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'r', 'r', '小林大和', 'general', '208', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 's', 's', '高橋', 'general', '209', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 't', 't', '中村翔太', 'general', '210', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'u', 'u', '渡辺花', 'general', '301', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'v', 'v', '伊藤', 'general', '302', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'w', 'w', '加藤蓮', 'general', '303', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'x', 'x', '山本さくら', 'general', '304', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'y', 'y', '田中', 'general', '305', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'z', 'z', '佐藤颯太', 'general', '306', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'aa', 'aa', '鈴木結菜', 'general', '307', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ab', 'ab', '高橋', 'general', '308', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ac', 'ac', '小林陽向', 'general', '309', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ad', 'ad', '中村杏', 'general', '310', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ae', 'ae', '渡辺', 'general', '401', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'af', 'af', '伊藤湊', 'general', '402', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ag', 'ag', '加藤莉子', 'general', '403', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ah', 'ah', '山本', 'general', '404', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ai', 'ai', '田中悠', 'general', '405', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'aj', 'aj', '佐藤陽菜乃', 'general', '406', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ak', 'ak', '鈴木', 'general', '407', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'al', 'al', '高橋陸斗', 'general', '408', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'am', 'am', '小林美羽', 'general', '409', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'an', 'an', '中村', 'general', '410', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ao', 'ao', '渡辺晴翔', 'general', '501', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ap', 'ap', '伊藤心春', 'general', '502', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'aq', 'aq', '加藤', 'general', '503', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ar', 'ar', '山本颯真', 'general', '504', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'as', 'as', '田中芽依', 'general', '505', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'at', 'at', '佐藤', 'general', '506', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'au', 'au', '鈴木朝陽', 'general', '507', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'av', 'av', '高橋凛', 'general', '508', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'aw', 'aw', '小林', 'general', '509', 'dentshowa', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ax', 'ax', '中村碧', 'general', '510', 'dentshowa', NULL, NOW(), NOW())
ON CONFLICT (email) DO UPDATE SET
  password = EXCLUDED.password,
  name = EXCLUDED.name,
  role = EXCLUDED.role,
  assigned_room_number = EXCLUDED.assigned_room_number,
  university_code = EXCLUDED.university_code,
  updated_at = NOW();
